export default [
  {
    id: 1,
    single: true,
    title: 'Tenzies',
    desc: 'Win the game when all dice have the same number of dots.',
    screens: ['tenzies', 'tenzies-show'],
    page: 'https://malelus.github.io/Tenzies',
    github: 'https://github.com/Malelus/Tenzies',
  },
  {
    id: 2,
    single: true,
    title: 'Quizzical',
    desc: 'Test your knowledge in different categories.',
    screens: ['quizzical', 'quizzical-show'],
    page: 'https://malelus.github.io/Quizzical',
    github: 'https://github.com/Malelus/Quizzical',
  },
  {
    id: 3,
    single: true,
    title: 'Task Tracker',
    desc: 'Easy to use application to create tasks.',
    screens: ['task-tracker', 'task-tracker-show'],
    page: 'https://malelus.github.io/TaskTracker',
    github: 'https://github.com/Malelus/TaskTracker',
  },
  {
    id: 4,
    single: false,
    group_title: 'Other projects',
    title: ['Kwadratowa Padew', 'Emoticons', 'Ryszard Szurkowski', 'Covid-19 Vaccines'],
    group_desc: 'Projects from school and hobbyist.',
    desc: [
      'Minecraft server site of Kwadratowa Padew',
      'A site about Emoticons and their importance in communication.',
      'A site about cyclist Ryszard Szurkowski.',
      'A page about the types of vaccines for COVID-19.',
    ],
    screens: [['kpadew'], ['emoticons'], ['szurkowski'], ['vaccines']],
    page: [
      'https://malelus.github.io/Project_KwadratowaPadew/',
      'https://malelus.github.io/Project_Emotikony/',
      'https://malelus.github.io/Project_RyszardSzurkowski/',
      'https://malelus.github.io/Project_SzczepionkiCovid/',
    ],
    github: [
      'https://github.com/Malelus/Project_KwadratowaPadew',
      'https://github.com/Malelus/Project_Emotikony',
      'https://github.com/Malelus/Project_RyszardSzurkowski',
      'https://github.com/Malelus/Project_SzczepionkiCovid',
    ],
  },
];
